<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com</groupId>
        <artifactId>xiyu</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>xiyu-server</artifactId>
    <packaging>war</packaging>

    <name>${project.artifactId}</name>
    <url>https://github.com/YunaiV/ruoyi-vue-pro</url>

    <properties>
        <!-- 统一依赖管理 -->
        <spring.boot.version>3.4.1</spring.boot.version>
        <!-- DB 相关 -->
        <jimmer.version>0.9.9</jimmer.version>
        <flyway.version>11.1.0</flyway.version>
        <mysql.connector.version>8.0.22</mysql.connector.version>
        <!-- 监控相关 -->
        <spring.boot.websocket.version>3.4.1</spring.boot.websocket.version>
        <opentracing.version>0.33.0</opentracing.version>
        <spring.boot.admin.version>3.4.1</spring.boot.admin.version>
        <!-- 工具类相关 -->
        <captcha-plus.version>2.0.3</captcha-plus.version>
        <jsoup.version>1.15.4</jsoup.version>
        <lombok.version>1.18.30</lombok.version>
        <mapstruct.version>1.5.3.Final</mapstruct.version>
        <hutool.version>5.8.15</hutool.version>
        <easyexcel.verion>3.2.1</easyexcel.verion>
        <velocity.version>2.3</velocity.version>
        <screw.version>1.0.5</screw.version>
        <guava.version>31.1-jre</guava.version>
        <guice.version>5.1.0</guice.version>
        <transmittable-thread-local.version>2.14.2</transmittable-thread-local.version>
        <commons-net.version>3.8.0</commons-net.version>
        <jsch.version>0.1.55</jsch.version>
        <tika-core.version>2.7.0</tika-core.version>
        <jackson.version>2.15.2</jackson.version>
        <slf4j.version>2.0.16</slf4j.version>
        <micrometer.registry.prometheus.version>1.9.9</micrometer.registry.prometheus.version>
        <!-- 三方云服务相关 -->
        <okio.version>3.0.0</okio.version>
        <okhttp3.version>4.10.0</okhttp3.version>
        <minio.version>8.5.2</minio.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- 统一依赖管理 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring.boot.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>
    <dependencies>
        <!-- 统一依赖管理 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-dependencies</artifactId>
            <version>${spring.boot.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com</groupId>
            <artifactId>xiyu-service</artifactId>
            <version>${revision}</version>
        </dependency>
    </dependencies>


    <build>
        <!-- 设置构建的 jar 包名 -->
        <finalName>${project.artifactId}</finalName>
        <plugins>
            <!-- 打包 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.4.1</version> <!-- 如果 spring.boot.version 版本修改，则这里也要跟着修改 -->
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal> <!-- 将引入的 jar 打入其中 -->
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
